#
# Application name and list of source files
#

NAME=voc2graph
CCSRCS=$(NAME).cpp

#
# Dependency libraries
#

USER_CFLAGS=-DRN_USE_CSPARSE
PKG_LIBS=-lGSV -lR3Graphics -lR3Shapes -lR2Shapes -lRNMath -lRNBasics -lCSparse -ljpeg -lpng -lgco

#
# R3 application makefile
#

include ../../makefiles/Makefile.apps
