#
# Application name and list of source files.
#

NAME=gsvlabel
CCSRCS=$(NAME).cpp \
  parse.cpp assignment.cpp \
  detection.cpp segmentation.cpp \
  label.cpp model.cpp \
  pointset.cpp point.cpp \
  align.cpp descriptor.cpp



#
# Dependency libraries
#

PKG_LIBS=-lGSV -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng


#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


