#
# Application name 
#

NAME=nsview



#
# Source files
#

CCSRCS=$(NAME).cpp R3GridArray.cpp



#
# Libraries
#

PKG_LIBS=-lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -lfglut -ljpeg -lpng



#
# Include standard makefile
#

include ../../makefiles/Makefile.apps















