#
# Makefile for GAPS apps
#

opt:
	$(MAKE) target "TARGET=$@"

debug:
	$(MAKE) target "TARGET=$@"

clean:
	$(MAKE) target "TARGET=$@"

release:
	mkdir -p ../release/apps
	cp Makefile ../release/apps
	$(MAKE) target "TARGET=$@"

target: 
	cd aggregate; $(MAKE) $(TARGET)
	cd aligngsv; $(MAKE) $(TARGET)
	cd autolabel; $(MAKE) $(TARGET)
	cd bboxget; $(MAKE) $(TARGET)
	cd boxinter; $(MAKE) $(TARGET)
	cd boxview; $(MAKE) $(TARGET)
	cd checkbbox; $(MAKE) $(TARGET)
	cd cmpimgs; $(MAKE) $(TARGET)
	cd cmppfms; $(MAKE) $(TARGET)
	cd converttruth; $(MAKE) $(TARGET)
	cd cor2cor; $(MAKE) $(TARGET)
	cd cor2map; $(MAKE) $(TARGET)
	cd coreval; $(MAKE) $(TARGET)
	cd correlateImages; $(MAKE) $(TARGET)
	cd corview; $(MAKE) $(TARGET)
	cd createlaser; $(MAKE) $(TARGET)
	cd dadetect; $(MAKE) $(TARGET)
	cd evalfunc; $(MAKE) $(TARGET)
	cd evalpfm; $(MAKE) $(TARGET)
	cd evalpred; $(MAKE) $(TARGET)
	cd generateGrid; $(MAKE) $(TARGET)
	cd grd2grd; $(MAKE) $(TARGET)
	cd grd2msh; $(MAKE) $(TARGET)
	cd grd2pts; $(MAKE) $(TARGET)
	cd grd2txt; $(MAKE) $(TARGET)
	cd grdview; $(MAKE) $(TARGET)
	cd gsv2gsv; $(MAKE) $(TARGET)
	cd gsv2msh; $(MAKE) $(TARGET)
	cd gsv2pgrd; $(MAKE) $(TARGET)
	cd gsvalign; $(MAKE) $(TARGET)
	cd gsvcorview; $(MAKE) $(TARGET)
	cd gsvinfo; $(MAKE) $(TARGET)
	cd gsvlabel; $(MAKE) $(TARGET)
	cd gsvsegment; $(MAKE) $(TARGET)
	cd gsvshow; $(MAKE) $(TARGET)
	cd gsvview; $(MAKE) $(TARGET)
	cd hough; $(MAKE) $(TARGET)
	cd houghvote; $(MAKE) $(TARGET)
	cd img2img; $(MAKE) $(TARGET)
	cd msh2cor; $(MAKE) $(TARGET)
	cd msh2grd; $(MAKE) $(TARGET)
	cd msh2msh; $(MAKE) $(TARGET)
	cd msh2prp; $(MAKE) $(TARGET)
	cd msh2pts; $(MAKE) $(TARGET)
	cd mshalign; $(MAKE) $(TARGET)
	cd mshinfo; $(MAKE) $(TARGET)
	cd mshview; $(MAKE) $(TARGET)
	cd obj2grd; $(MAKE) $(TARGET)
	cd objdetect; $(MAKE) $(TARGET)
	cd orderview; $(MAKE) $(TARGET)
	cd pdb2grd; $(MAKE) $(TARGET)
	cd pdb2msh; $(MAKE) $(TARGET)
	cd pdb2pdb; $(MAKE) $(TARGET)
	cd pdbinfo; $(MAKE) $(TARGET)
	cd pdbview; $(MAKE) $(TARGET)
	cd pfm2pfm; $(MAKE) $(TARGET)
	cd pfminfo; $(MAKE) $(TARGET)
	cd pfmview; $(MAKE) $(TARGET)
	cd projtruth; $(MAKE) $(TARGET)
	cd projview; $(MAKE) $(TARGET)
	cd prp2prp; $(MAKE) $(TARGET)
	cd prpview; $(MAKE) $(TARGET)
	cd ptsview; $(MAKE) $(TARGET)
	cd sa2da; $(MAKE) $(TARGET)
	cd sadetect; $(MAKE) $(TARGET)
	cd sadetectpost; $(MAKE) $(TARGET)
	cd sadetectsetup; $(MAKE) $(TARGET)
	cd sagauss; $(MAKE) $(TARGET)
	cd sasetup; $(MAKE) $(TARGET)
	cd scninfo; $(MAKE) $(TARGET)
	cd scnview; $(MAKE) $(TARGET)
	cd sfl2img; $(MAKE) $(TARGET)
	cd sfl2sfl; $(MAKE) $(TARGET)
	cd sfldetect; $(MAKE) $(TARGET)
	cd sflinfo; $(MAKE) $(TARGET)
	cd sflinit; $(MAKE) $(TARGET)
	cd sflprocess; $(MAKE) $(TARGET)
	cd sflsegment; $(MAKE) $(TARGET)
	cd sflvalidate; $(MAKE) $(TARGET)
	cd sflview; $(MAKE) $(TARGET)
	cd training; $(MAKE) $(TARGET)
	cd txt2grd; $(MAKE) $(TARGET)
	cd voc2graph; $(MAKE) $(TARGET)
	cd voc2gsv; $(MAKE) $(TARGET)
	cd voc2opt; $(MAKE) $(TARGET)









